repo: https://github.com/karpathy/ng-video-lecture

In [212]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

import logging
import sys

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    force=True, 
    handlers=[logging.StreamHandler(sys.stdout)]
)

logger = logging.getLogger(__name__)
logger.info("Logger is active and printing to Jupyter!")

2026-03-01 19:31:30,662 - __main__ - INFO - Logger is active and printing to Jupyter!


## tokenizer

In [361]:
from nanogpt.tokenizer import CharTokenizer

In [362]:
sorted(set(["a", "1", "[UNK]", " ", "\n", "A"]))

['\n', ' ', '1', 'A', '[UNK]', 'a']

In [363]:
tokenizer = CharTokenizer(full_text)

In [ ]:
print(tokenizer.encode("9"))
print(tokenizer.decode(torch.Tensor([10, 65])))
tokenizer.decode(tokenizer.encode("wlekjr iowe9r 990e 0-we ..."))

tensor([65])
:[UNK]


'wlekjr iowe[UNK]r [UNK][UNK][UNK]e [UNK]-we ...'

## Data loader

In [364]:
from nanogpt.dataloader import DataLoader

In [342]:
dl = DataLoader(tokenizer=tokenizer)

2026-03-01 21:49:34,568 - __main__ - INFO - loaded https://raw.githubusercontent.com/karpathy/ng-video-lecture/master/input.txt.
Example:

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [344]:
dl.load_batch(split='val', context_length=8, batch_size=3)

(tensor([[ 1, 47, 57,  1, 51, 53, 57, 58],
         [46,  8,  0, 14, 43,  1, 54, 39],
         [53,  1, 39,  1, 42, 43, 58, 43]]),
 tensor([[47, 57,  1, 51, 53, 57, 58,  1],
         [ 8,  0, 14, 43,  1, 54, 39, 58],
         [ 1, 39,  1, 42, 43, 58, 43, 56]]))

In [260]:
dl.size

1115394

## BPE

In [222]:
import torch.nn as nn
from torch.nn import functional as F

In [366]:
from nanogpt.bpe import BPE

In [303]:
tokenizer.size

66

In [352]:
bpe = BPE(vocab_size=tokenizer.size)

In [353]:
output = bpe.generate(torch.tensor([[0], [1]], dtype=torch.long), 5)
print(output)
# tokenizer.decode(output)
print([tokenizer.decode(i) for i in output])

tensor([[ 0, 46, 37, 42, 37, 49],
        [ 1, 15, 40, 25, 44, 16]])
['\nhYdYk', ' CbMfD']


## Train

In [365]:
from nanogpt.trainer import approximate_loss

In [359]:
approximate_loss(bpe)

{'train': tensor(2.5298), 'val': tensor(2.4275)}

In [356]:
optimizer = torch.optim.AdamW(params=bpe.parameters(), lr=1e-3)

In [357]:
for step in range(10000):
    X, Y = dl.load_batch(8, 32)
    logits, loss = bpe(X, Y)

    optimizer.zero_grad(set_to_none=True)

    loss.backward()
    optimizer.step()

In [358]:
output = bpe.generate(torch.tensor([[55], [49], [35]], dtype=torch.long), 100)
out_s = [tokenizer.decode(i) for i in output]
for i in out_s:
    print(i)

qSiss hasut gede merire,
a?
DE d ke cishe! bepangFo?
s Imat. herisend tr ancO:
Than, XTit flwinsesing
ken aveppro ardcefan mly tatill3Win, ilcouprs le h gmeeerethe IENonies,
Diriougewiangerng n erurfou, 
Whun t hom'g-wire, t anthe therake bofrt hiese tsse f d r d til-olug, thedouxrsee
The temeanar DipesX
